[package]
name = "rust-coreutils"
version = "0.1.0"
authors = ["Katsuki Kobayashi <rare@tirasweel.org>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
libc = "0.2.0"
base64 = "0.9"
anyhow = "1.0"
thiserror = "1.0"
